/* ===== Mes cartes — version complète ===== */
const CARDS_KEY = 'loyalty_cards_v1';
const THEME_KEY = 'loyalty_theme_v2';
const COLORS = ['#2264d1', '#8b5cf6', '#e05252', '#e88b27', '#168c65', '#008da8', '#d04d91', '#475569'];
const THEMES = [
  { id:'light', name:'Clair', category:'light', description:'Propre et lumineux', swatch:'linear-gradient(135deg,#f4f7fb,#3268e8)' },
  { id:'sunset', name:'Coucher de soleil', category:'light', description:'Chaleureux et doux', swatch:'linear-gradient(135deg,#fff5f1,#ed6d5b)' },
  { id:'forest', name:'Forêt', category:'light', description:'Nature et calme', swatch:'linear-gradient(135deg,#eef8f2,#27975d)' },
  { id:'ocean', name:'Océan', category:'light', description:'Frais et moderne', swatch:'linear-gradient(135deg,#edf9fc,#008fa8)' },
  { id:'candy', name:'Bonbon', category:'light', description:'Rose et léger', swatch:'linear-gradient(135deg,#fff3f8,#ed5594)' },
  { id:'midnight', name:'Minuit', category:'dark', description:'Confortable le soir', swatch:'linear-gradient(135deg,#0e1525,#5c8df6)' },
  { id:'graphite', name:'Graphite', category:'dark', description:'Gris profond', swatch:'linear-gradient(135deg,#111318,#aeb8c7)' },
  { id:'purple-night', name:'Nuit violette', category:'dark', description:'Sombre et élégant', swatch:'linear-gradient(135deg,#151022,#b889ff)' },
  { id:'nord', name:'Nord', category:'dark', description:'Bleu ardoise', swatch:'linear-gradient(135deg,#202733,#88c0d0)' },
  { id:'ember', name:'Braise', category:'dark', description:'Sombre et chaleureux', swatch:'linear-gradient(135deg,#211414,#ff9b68)' },
  { id:'deep-ocean', name:'Océan profond', category:'dark', description:'Sombre et cyan', swatch:'linear-gradient(135deg,#071b27,#5ed6e6)' },
  { id:'mono', name:'Noir et blanc', category:'dark', description:'Minimaliste', swatch:'linear-gradient(135deg,#101010,#fff)' }
];
let cards=[], editingId=null, openedId=null, selectedColor=COLORS[0], selectedLogo=null, stream=null, detectorTimer=null;
const $=id=>document.getElementById(id);
function load(){try{cards=JSON.parse(localStorage.getItem(CARDS_KEY)||'[]')}catch{cards=[]}setTheme(localStorage.getItem(THEME_KEY)||'light',false);$('quickGuide').hidden=localStorage.getItem('loyalty_hide_guide')==='1'}
function save(){localStorage.setItem(CARDS_KEY,JSON.stringify(cards))}
function setTheme(theme,persist=true){document.body.dataset.theme=theme;if(persist)localStorage.setItem(THEME_KEY,theme);const colors={light:'#f4f7fb',midnight:'#0e1525',graphite:'#111318','purple-night':'#151022',nord:'#202733',ember:'#211414','deep-ocean':'#071b27',sunset:'#fff5f1',forest:'#eef8f2',ocean:'#edf9fc',candy:'#fff3f8',mono:'#101010'};$('themeColorMeta').content=colors[theme]||colors.light;renderThemes()}
function uid(){return`card_${Date.now()}_${Math.random().toString(36).slice(2,8)}`}
function initials(name){return name.trim().slice(0,2).toUpperCase()}
function escapeHtml(value){const el=document.createElement('span');el.textContent=value;return el.innerHTML}
function typeLabel(type){return type==='barcode'?'Code-barres':type==='qrcode'?'QR code':'Sans code'}
function darken(hex,amount=-30){const n=parseInt(hex.replace('#',''),16),c=v=>Math.max(0,Math.min(255,v+amount));return`#${((1<<24)+(c(n>>16)<<16)+(c((n>>8)&255)<<8)+c(n&255)).toString(16).slice(1)}`}
function render(){const grid=$('cardsGrid'),query=$('searchInput').value.trim().toLowerCase(),filtered=cards.filter(card=>card.name.toLowerCase().includes(query));grid.innerHTML='';$('cardCount').textContent=`${cards.length} carte${cards.length===1?'':'s'}`;$('emptyState').hidden=cards.length!==0||query.length===0;if(cards.length===0)$('emptyState').hidden=false;if(filtered.length===0&&cards.length>0){grid.innerHTML='<p class="no-result">Aucune carte trouvée.</p>';return}filtered.forEach((card,index)=>{const button=document.createElement('button');button.className='loyalty-card';button.type='button';button.style.setProperty('--card-color',card.color||COLORS[0]);button.style.setProperty('--card-color-dark',darken(card.color||COLORS[0]));button.style.animationDelay=`${index*45}ms`;button.setAttribute('aria-label',`Ouvrir la carte ${card.name}`);button.innerHTML=`<div class="card-logo">${card.logo?`<img src="${card.logo}" alt="Logo ${escapeHtml(card.name)}">`:escapeHtml(initials(card.name))}</div><div><p class="card-name">${escapeHtml(card.name)}</p><p class="card-type">${typeLabel(card.codeType)}</p></div><span class="card-arrow">›</span>`;button.addEventListener('click',()=>openDetail(card.id));grid.appendChild(button)})}
function showToast(message){const old=$('toast');if(old)old.remove();const toast=document.createElement('div');toast.id='toast';toast.className='toast';toast.textContent=message;document.body.appendChild(toast);setTimeout(()=>toast.remove(),2200)}
function showForm(id=null){editingId=id;const card=id?cards.find(item=>item.id===id):null;$('formTitle').textContent=card?'Modifier la carte':'Nouvelle carte';$('nameInput').value=card?.name||'';$('codeInput').value=card?.code||'';$('codeTypeInput').value=card?.codeType||'barcode';selectedColor=card?.color||COLORS[0];selectedLogo=card?.logo||null;updateLogoPreview();renderColors();openLayer('formSheet','formBackdrop');setTimeout(()=>$('nameInput').focus(),100)}
function closeForm(){closeLayer('formSheet','formBackdrop');editingId=null}
function openLayer(panel,backdrop){$(panel).hidden=false;$(backdrop).hidden=false;document.body.classList.add('no-scroll')}
function closeLayer(panel,backdrop){$(panel).hidden=true;$(backdrop).hidden=true;document.body.classList.remove('no-scroll')}
function renderColors(){$('colorRow').innerHTML=COLORS.map(color=>`<button type="button" class="color-dot ${color===selectedColor?'selected':''}" style="background:${color}" data-color="${color}" aria-label="Choisir la couleur"></button>`).join('');$('colorRow').querySelectorAll('.color-dot').forEach(dot=>dot.addEventListener('click',()=>{selectedColor=dot.dataset.color;$('customColorInput').value=selectedColor;renderColors()}));$('customColorInput').value=selectedColor}
function updateLogoPreview(){const preview=$('logoPreview');if(selectedLogo){preview.innerHTML=`<img src="${selectedLogo}" alt="Logo sélectionné">`;$('removeLogo').hidden=false}else{preview.innerHTML='<span>🏪</span>';$('removeLogo').hidden=true}}
function resizeLogo(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=event=>{const image=new Image();image.onload=()=>{const size=320,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,size,size);const scale=Math.min(size/image.width,size/image.height),width=image.width*scale,height=image.height*scale;ctx.drawImage(image,(size-width)/2,(size-height)/2,width,height);resolve(canvas.toDataURL('image/jpeg',.84))};image.onerror=reject;image.src=event.target.result};reader.readAsDataURL(file)})}
function saveCard(event){event.preventDefault();const name=$('nameInput').value.trim();if(!name)return showToast('Ajoute le nom du magasin.');const data={name,code:$('codeInput').value.trim(),codeType:$('codeTypeInput').value,color:selectedColor,logo:selectedLogo};if(editingId)Object.assign(cards.find(card=>card.id===editingId),data);else cards.push({id:uid(),...data,createdAt:Date.now()});try{save()}catch{return showToast('Stockage plein : choisis un logo plus léger.')}render();closeForm();showToast('Carte enregistrée ✓')}
function openDetail(id){openedId=id;const card=cards.find(item=>item.id===id);if(!card)return;$('detailName').textContent=card.name;$('detailType').textContent=typeLabel(card.codeType);$('detailCode').textContent=card.code||'';$('detailLogo').innerHTML=card.logo?`<img src="${card.logo}" alt="Logo ${escapeHtml(card.name)}">`:escapeHtml(initials(card.name));$('barcodeCanvas').style.display='none';$('qrHolder').innerHTML='';if(card.code&&card.codeType==='barcode'&&window.JsBarcode){try{$('barcodeCanvas').style.display='block';JsBarcode('#barcodeCanvas',card.code,{format:'CODE128',displayValue:false,height:82,width:2,margin:5})}catch{}}if(card.code&&card.codeType==='qrcode'&&window.QRCode)new QRCode($('qrHolder'),{text:card.code,width:190,height:190});$('detailPanel').hidden=false;$('detailBackdrop').hidden=false;document.body.classList.add('no-scroll')}
function closeDetail(){$('detailPanel').hidden=true;$('detailBackdrop').hidden=true;document.body.classList.remove('no-scroll');openedId=null}
function renderThemes(){const current=document.body.dataset.theme;const section=(category,title,description)=>{const items=THEMES.filter(theme=>theme.category===category).map(theme=>`<button type="button" class="theme-option ${theme.id===current?'active':''}" data-theme="${theme.id}"><span class="theme-swatch" style="background:${theme.swatch}"></span><span class="theme-info"><strong>${theme.name}</strong><small>${theme.description}</small></span><span class="theme-check">${theme.id===current?'✓':''}</span></button>`).join('');return`<div class="theme-category"><div class="theme-category-heading"><h3>${title}</h3><p>${description}</p></div><div class="theme-category-list">${items}</div></div>`};$('themeList').innerHTML=section('light','☀️ Clair','Des couleurs lumineuses')+section('dark','🌙 Sombre','Confortable dans le noir');$('themeList').querySelectorAll('.theme-option').forEach(item=>item.addEventListener('click',()=>setTheme(item.dataset.theme)))}
async function openScanner(){if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia)return showToast('Scanner indisponible : saisis le code manuellement.');$('scanner').hidden=false;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});$('scanVideo').srcObject=stream;const detector=new BarcodeDetector({formats:['qr_code','code_128','ean_13','ean_8','upc_a','upc_e','code_39']});detectorTimer=setInterval(async()=>{try{const result=await detector.detect($('scanVideo'));if(!result.length)return;$('codeInput').value=result[0].rawValue;$('codeTypeInput').value=result[0].format==='qr_code'?'qrcode':'barcode';closeScanner();showToast('Code trouvé ✓')}catch{}},350)}catch{closeScanner();showToast('Autorise la caméra pour scanner.')}}
function closeScanner(){$('scanner').hidden=true;if(detectorTimer)clearInterval(detectorTimer);detectorTimer=null;if(stream)stream.getTracks().forEach(track=>track.stop());stream=null}
$('addButton').addEventListener('click',()=>showForm());$('emptyAddButton').addEventListener('click',()=>showForm());$('closeForm').addEventListener('click',closeForm);$('cancelForm').addEventListener('click',closeForm);$('formBackdrop').addEventListener('click',closeForm);$('cardForm').addEventListener('submit',saveCard);$('searchInput').addEventListener('input',render);$('hideGuide').addEventListener('click',()=>{$('quickGuide').hidden=true;localStorage.setItem('loyalty_hide_guide','1')});$('chooseLogo').addEventListener('click',()=>$('logoInput').click());$('logoPreview').addEventListener('click',()=>$('logoInput').click());$('logoInput').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{selectedLogo=await resizeLogo(file);updateLogoPreview();showToast('Logo ajouté ✓')}catch{showToast('Image impossible à utiliser.')}event.target.value=''});$('removeLogo').addEventListener('click',()=>{selectedLogo=null;updateLogoPreview()});$('customColorInput').addEventListener('input',event=>{selectedColor=event.target.value;renderColors()});$('themeButton').addEventListener('click',()=>{renderThemes();openLayer('themeSheet','themeBackdrop')});$('closeTheme').addEventListener('click',()=>closeLayer('themeSheet','themeBackdrop'));$('themeBackdrop').addEventListener('click',()=>closeLayer('themeSheet','themeBackdrop'));$('closeDetail').addEventListener('click',closeDetail);$('closeDetailButton').addEventListener('click',closeDetail);$('detailBackdrop').addEventListener('click',closeDetail);$('editCard').addEventListener('click',()=>{const id=openedId;closeDetail();showForm(id)});$('deleteCard').addEventListener('click',()=>{if(!openedId||!confirm('Supprimer cette carte ?'))return;cards=cards.filter(card=>card.id!==openedId);save();render();closeDetail();showToast('Carte supprimée.')});$('scanButton').addEventListener('click',openScanner);$('closeScanner').addEventListener('click',closeScanner);
load();render();
